---

- hosts: all
  become: yes
  tasks:

  - name: Instalando Apache + soporte PHP y Midnight Commander
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - "{{ mc_package }}"
      state: latest
      update_cache: yes
