---

- hosts: all
  become: yes
  tasks:

  - name: Actualizar el repository index
    apt:
      update_cache: yes

  - name: Desinstalando Apache2
    apt:
      name: apache2
      state: absent

  - name: Quitar soporte PHP para Apache
    apt:
      name: libapache2-mod-php
      state: absent
