---

- hosts: all
  become: true
  pre_tasks:
  - name: Instalar actualizaciones (Fedora)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: Instalar actualizaciones (Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: web_server
  become: true
  tasks:
  - name: Instalar Apache y PHP para servers Debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: Instalar Apache y PHP para Fedora
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"

- hosts: db_server
  become: true
  tasks:

  - name: Instalar mardiadb (Fedora)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Instalar mardiadb (Debian)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

- hosts: file_server
  become: true
  tasks:

  - name: Instalar SAMBA
    package:
      name: samba
      state: latest
